accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

board/urls.py
from django.urls import path, include
from . import views
app_name = 'board'

urlpatterns = [
    path('1/', views.notice, name='notice'),
    path('<int:board_id>/article/<int:article_id>/', views.article_detail, name='detail'),
    path('<int:board_id>/article/<int:article_id>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:board_id>/article/<int:article_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_id>/write/', views.article_write, name='write'),
    path('<int:article_id>/modify/', views.article_modify, name='modify'),
    path('<int:article_id>/delete/', views.article_delete, name='delete'),
    path('article/like/', views.article_like, name='article_like')
]

base/views.py
from django.http import HttpRequest
from django.shortcuts import render


def index(request: HttpRequest):

    return render(request, "home/main.html")

base/templates/_form.html
{% load django_bootstrap5 %}

<div class="card">
    {% if form_title %}
    <div class="card-header">
        {{ form_title }}
    </div>
    {% endif %}
    <div class="card-body">
        {% if form %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {% bootstrap_form form %}
            <button type="submit" class="btn btn-primary">
                {{ submit_label|default:"Submit" }}
            </button>
        </form>
        {% else %}
        <div class="alert alert-danger">
            form 객체를 지정해주세요.
        </div>
        {% endif %}
    </div>
</div>

base/templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

base/templates/layout.html
<!doctype html>
{% load static %}
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>밍크</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <link rel="stylesheet" href="{% static 'common.css' %}">
    <script defer src="{% static 'common.js' %}"></script>
</head>
<body>
{% if messages %}
{% for message in messages %}
<div class="alert alert-{{ message.tags }} t-my-[0px]">
    {{ message }}
</div>
{% endfor %}
{% endif %}
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <!-- Site Logo Here -->
            <a class="navbar-brand" href="{%url 'index' %}">밍크</a>
            <!-- Mobile Toggle Button -->
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarMobileToggle"
                    aria-controls="navbarMobileToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarMobileToggle">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'board:notice' %}">공지사항</a>
                    </li>
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'accounts:logout' %}">{{ user.username }}(로그아웃)</a>
                        {% else %}
                        <a class="nav-link" href="{% url 'accounts:login'%}">로그인</a>
                        {% endif %}
                    </li>
                </ul>

                <!-- Right Side -->
                <div class="btn-group float-end">
                    <a href="#" class="dropdown-toggle text-decoration-none text-light" data-bs-toggle="dropdown">
                        <i class="bi bi-person-circle"></i>
                        <span>Gurdeep Singh</span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end">
                        <li><a href="#" class="dropdown-item"><i class="bi bi-lock-fill"></i> Change Password</a></li>
                        <li><a href="#" class="dropdown-item"><i class="bi bi-gear-fill"></i> Admin Setion</a></li>
                        <li><a href="#" class="dropdown-item"><i class="bi bi-gear-wide-connected"></i> IMAP
                            Settings</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a href="#" class="dropdown-item"><i class="bi bi-box-arrow-right"></i> Sign out</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
</header>

{%block content%}
{%endblock%}

</body>
</html>