base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

board/urls.py
from django.urls import path, include
from . import views
app_name = 'board'

urlpatterns = [
    path('1/', views.notice, name='notice'),
    path('<int:board_id>/article/<int:article_id>/', views.article_detail, name='detail'),
    path('<int:board_id>/article/<int:article_id>/comment/write/', views.comment_write, name='comment_write'),
    path('<int:board_id>/article/<int:article_id>/comment/<int:comment_id>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:board_id>/write/', views.article_write, name='write'),
    path('<int:article_id>/modify/', views.article_modify, name='modify'),
    path('<int:article_id>/delete/', views.article_delete, name='delete'),
    path('article/like/', views.article_like, name='article_like')
]

board/models.py
from django.db import models
from accounts.models import User


# Create your models here.
class Board(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    name = models.CharField('상품명(내부용)', max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('수정날짜', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_article')
    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    subject = models.CharField('제목', max_length=100)
    content = models.TextField('내용')
    is_blind = models.BooleanField('공개 여부', default=False)
    voter = models.ManyToManyField(User, related_name='voter_article')

    def count_voter_user(self):  # total likes_user
        return self.voter.count()

    def __str__(self):
        return self.subject

    @property
    def like_count(self):
        return self.like_user_set.count()


class Comment(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('수정날짜', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user_comment')
    content = models.TextField('내용')
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    is_modify = models.BooleanField('수정 가능 여부', default=False)
    voter = models.ManyToManyField(User, related_name='voter_comment')
    def __str__(self):
        return self.content

board/forms.py
from django import forms
from board.models import Article, Board, Comment


class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article  # 사용할 모델
        board = Board
        fields = ['board', 'subject', 'content' ]

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment  # 사용할 모델
        fields = [ 'content' ]

board/views.py
# Create your views here.
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.db.models import Q
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .forms import ArticleForm, CommentForm
from board.models import Board, Article, Comment


def notice(request: HttpRequest):
    board = Board.objects.get(name="공지사항")

    return article_list(request, board)


def article_list(request: HttpRequest, board):
    kw = request.GET.get('kw', '')
    page = request.GET.get('page', '1')  # 페이지

    if not kw:
        article_list = Article.objects.filter(board=board.id).order_by('-id')
    else:
        article_list = Article.objects.filter(board=board.id, ).filter(
            Q(subject__icontains=kw) | Q(content__icontains=kw)).order_by('-id')

    paginator = Paginator(article_list, 10)  # 페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'article_list': page_obj,
               'board': board,
               }
    return render(request, 'board/article_list.html', context)


def article_detail(request: HttpRequest, board_id, article_id):
    article = get_object_or_404(Article, id=article_id)
    board = get_object_or_404(Board, id=article.board_id)
    comment = Comment.objects.filter(article_id=article_id)
    context = {'article': article,
               'board': board,
               'comment': comment}
    return render(request, 'board/article_detail.html', context)


@login_required
def article_write(request: HttpRequest, board_id):
    if request.user.is_authenticated:
        board = Board.objects.get(id=board_id)
        returnUrl = f"/board/{board.id}"
        if request.method == 'POST':
            form = ArticleForm(request.POST)
            if form.is_valid():
                article = form.save(commit=False)
                article.board_id = board.id
                article.user_id = request.user.id
                article.save()
                return redirect(returnUrl)
        else:
            form = ArticleForm()
        context = {'form': form,
                   'board': board}
        return render(request, 'board/article_form.html', context)
    else:
        return redirect('accounts:login')


@login_required
def article_modify(request: HttpRequest, article_id):
    article = get_object_or_404(Article, id=article_id)
    board_id = article.board_id
    board = get_object_or_404(Board, id=board_id)
    if request.method == "POST":
        form = ArticleForm(request.POST, instance=article)
        if form.is_valid():
            form.save()
            messages.success(request, "질문이 수정되었습니다.")
            return redirect(f"/board/{board_id}")
    else:
        form = ArticleForm(None, instance=article)

    return render(request, "board/article_form.html", {
        "form": form,
        "board": board,
    })

@login_required
def article_delete(request: HttpRequest, article_id):
    article = get_object_or_404(Article, id=article_id)
    board_id = article.board_id
    article.delete()
    messages.success(request, "질문이 삭제되었습니다.")
    return redirect(f"/board/{board_id}")


@login_required
def comment_write(request: HttpRequest, board_id, article_id):
    board = get_object_or_404(Board, id=board_id)
    article = get_object_or_404(Article, id=article_id)

    if request.user.is_authenticated:
        returnUrl = f"/board/{article.board_id}/article/{article.id}/"
        if request.method == 'POST':
            form = CommentForm(request.POST)
            if form.is_valid():
                comment = form.save(commit=False)
                comment.article_id = article.id
                comment.user_id = request.user.id
                comment.save()
                return redirect(returnUrl)
        else:
            form = CommentForm()
        context = {'form': form,
                   'board': board,
                   'article': article,
                   }
        return render(request, 'board/article_detail.html', context)
    else:
        return redirect('accounts:login')


@login_required
def comment_delete(request: HttpRequest, board_id, article_id, comment_id):
    comment = Comment.objects.get(id=comment_id)
    board_id = comment.article.board_id
    comment.delete()
    messages.success(request, "댓글이 삭제되었습니다.")
    return redirect(f"/board/{board_id}/article/{article_id}/")


@login_required
@require_POST
def article_like(request):
    pk = request.POST.get('pk', None)
    article = get_object_or_404(Article, pk=pk)
    user = request.user

    if article.voter.filter(id=user.id).exists():
        article.voter.remove(user)
        message = '좋아요 취소'
    else:
        article.voter.add(user)
        message = '좋아요'

    context = {'likes_count':article.count_voter_user(), 'message': message}
    return HttpResponse(json.dumps(context), content_type="application/json")

board/templates/board/article_detail.html
{% extends "layout.html" %}

{%block content%}
<div class="container" style="margin-top:50px;">
    <div><a href="#" class="fs-1">{{board.name}}</a></div>
    <hr>
    <div class="card">
        <div class="card-header">
            {{article.subject}}
        </div>

        <div class="card-body text-center">
            <p class="card-text" style="text-align:left;">{{article.content}}</p>
            <button class="btn btn-primary like" name="{{article.id}}"><i class="far fa-thumbs-up" style="display:inline;"></i>
                <p id="count-{{ article.id }}" style="display:inline;">{{ article.voter.all.count }}</p>
            </button>
        </div>

        <div class="card-footer text-muted">
            {{article.reg_date}}
        </div>
    </div>
    <div style="margin-top:30px;">전체 댓글
        {% if article.comment_set.count > 0 %}
        <span style="color:blue;">
            {{ article.comment_set.count }}
        </span>
        {%else%}
        0
        {% endif %}개
    </div>
    <div class="container" style="margin-top:50px;">
        {% for comment_ in comment %}
        <div style="height:30px; text-align:left; background-color:gray;">
            <p class="fs-6" style="line-height:30px;">{{ comment_.user.username }}{{ comment_.reg_date}}
                {% if request.user.id == comment_.user.id %}
                <a href="{% url 'board:comment_delete' board.id article.id comment_.id %}"
                   onclick="if ( confirm('정말 삭제하시겠습니까?') == false ) return false"><i
                        class="fas fa-trash-alt"></i></a></td>
                {%endif%}
            </p>
        </div>
        <div class="" style="height:100px;">
            {{ comment_.content }}
        </div>
        {%endfor%}
    </div>

    <div>
        <form method="post" action="{% url 'board:comment_write' board.id article.id%}">
            {% csrf_token %}
            <div class="form-group">
                <label for="content"></label>
                <textarea class="form-control" name="content"
                          id="content" rows="4"
                          placeholder="내용을 입력하세요.">{{ form.content.value|default_if_none:'' }}</textarea>
            </div>
            <button type="submit" class="btn btn-primary" style="margin-top:10px; margin-bottom:10px;">등록</button>
        </form>
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script type="text/javascript">
    $(".like").click(function () { // .like 버튼을 클릭 감지
        var pk = $(this).attr('name')
        $.ajax({ // ajax로 서버와 통신
            type: "POST", // 데이터를 전송하는 방법
            url: "{% url 'board:article_like' %}", // 통신할 url을 지정
            data: { 'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}' }, // 서버로 데이터 전송시 옵션, pk를 넘겨야 어떤 video인지 알 수 있음
            dataType: "json",
            success: function (response) { // 성공
                $("#count-" + pk).html(response.likes_count); // 좋아요 개수 변경
            },
            error: function (request, status, error) { // 실패
                alert("로그인이 필요합니다.")
                window.location.replace("/accounts/login/") // 로그인 페이지로 넘어가기
            },
        });
    })

</script>
{% endblock%}

board/templates/board/article_form.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">게시글 등록</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

board/templates/board/article_list.html
{% extends "layout.html" %}

{%block content%}
<div class="container-lg">
    <div class="input-group" style="margin-top:30px;">
        <div class="form-outline">
            <form class="d-flex">
                <input class="form-control me-2" type="search" name="kw" placeholder="검색어를 입력해주세요."
                       aria-label="Search"
                       value="{{request.GET.kw}}">
                <button type="button" class="btn btn-primary">
                    <i class="fas fa-search"></i>
                </button>
            </form>
        </div>
    </div>
    <table class="table" style="margin-top:30px;">
        <thead>
        <tr>
            <th scope="col">번호</th>
            <th scope="col">제목</th>
            <th scope="col">글쓴이</th>
            <th scope="col">추천수</th>
            <th scope="col">날짜</th>
        </tr>
        </thead>
        <tbody>
        {% for article in article_list%}
        <tr>
            <th scope="row"><h6>{{ article.id }}</h6></th>
            <td><a href="{% url 'board:detail' article.board_id article.id %}">{{ article.subject }}</a></td>
            <td><a href="#">{{ article.user.username }}</a></td>
            <td><h6>{{article.voter.count}}</h6></td>
            <td><h6>{{ article.reg_date }}</h6></td>
            {% if request.user.id == article.user.id %}
            <td><a href="{% url 'board:modify' article.id %}" class="btn btn-outline-primary"
                   style="margin-right:10px;">수정</a>
                <a href="{% url 'board:delete' article.id %}" class="btn btn-warning"
                   onclick="if ( confirm('정말 삭제하시겠습니까?') == false ) return false">삭제</a></td>
            {%endif%}
        </tr>
        {%endfor%}
        </tbody>
    </table>
    <div>
        <a href=" {% url 'board:write' board.id%}" class="btn btn-primary" style="margin-top:30px;">글 작성</a>
    </div>
    <ul class="pagination justify-content-center" style="margin-top:50px;">
        <!-- 이전페이지 -->
        {% if article_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.previous_page_number }}&kw={{request.GET.kw}}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in article_list.paginator.page_range %}
        {% if article_list.number|add:-5 <= page_number <= article_list.number|add:5 %}
        {% if page_number == article_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}&kw={{request.GET.kw}}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}&kw={{request.GET.kw}}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.next_page_number }}&kw={{request.GET.kw}}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
{%endblock%}

board/templates/board/detail.html
{% extends "layout.html" %}

board/templates/board/list.html
{% extends "layout.html" %}

{%block content%}

<div class="container-lg" style="margin-top:100px;">
    <form class="d-flex" action="{% url 'board:notice'%}">
        <input class="form-control me-2" type="search" name="kw" placeholder="검색어를 입력해주세요."
               aria-label="Search"
               value="{{request.GET.kw}}">
        <button class="btn btn-outline-success" type="submit">검색</button>
    </form>
    <ul style="margin-top:50px;">
        {% for article in article_list%}
        <li>
            <a href="{% url 'board:detail' article.id %}">{{ article.subject }}</a>
        </li>
        {%endfor%}
    </ul>
    <ul class="pagination justify-content-center" style="margin-top:50px;">
        <!-- 이전페이지 -->
        {% if article_list.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.previous_page_number }}&kw={{request.GET.kw}}">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in article_list.paginator.page_range %}
        {% if article_list.number|add:-5 <= page_number <= article_list.number|add:5 %}
        {% if page_number == article_list.number %}
        <li class="page-item active" aria-current="page">
            <a class="page-link" href="?page={{ page_number }}&kw={{request.GET.kw}}">{{ page_number }}</a>
        </li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page_number }}&kw={{request.GET.kw}}">{{ page_number }}</a>
        </li>
        {% endif %}
        {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if article_list.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ article_list.next_page_number }}&kw={{request.GET.kw}}">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
</div>
{%endblock%}