accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

base/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('board/', include('board.urls')),
    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    first_name = None
    last_name = None
    name = models.CharField('이름', max_length=100)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.forms import forms

from accounts.models import User


class SignupForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].required = True
        self.fields['name'].required = True

    class Meta(UserCreationForm.Meta):
        model = User
        fields = ['username', 'email', 'name']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email:
            qs = User.objects.filter(email=email)
            if qs.exists():
                raise forms.ValidationError("이미 등록된 이메일 주소입니다.")
        return email

accounts/views.py
from django.contrib.auth.views import LoginView
from django.http import HttpRequest
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import login as auth_login
from .decorators import logout_required

# Create your views here.
from accounts.forms import SignupForm

@logout_required
def login(request: HttpRequest):
    return LoginView.as_view(template_name="accounts/login.html")(request)

@logout_required
def signup(request: HttpRequest):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            signed_user = form.save()
            auth_login(request, signed_user)
            messages.success(request, "회원가입 환영합니다.")
            # signed_user.send_welcome_email()  # FIXME: Celery로 처리하는 것을 추천.
            next_url = request.GET.get('next', '/')
            return redirect('index')
    else:
        form = SignupForm()
    return render(request, 'accounts/signup.html', {
        'form': form,
    })

accounts/templates/accounts/login.html
{% extends "layout.html" %}
{% block content %}
<div class="container">
  <div class="row"></div>
        <div class="col-md-4 offset-md-4">
            <div class="login-form bg-light mt-4 p-4">
                <form method="post" action="{% url 'accounts:login' %}" class="row g-3">
                    <h4>Welcome Back</h4>
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="col-12">
                        <label for="username">사용자 ID</label>
                        <input type="text" name="username" class="form-control" placeholder="Username" id="username"
                               value="{{ form.username.value|default_if_none:'' }}">
                    </div>
                    <div class=" col-12">
                        <label for="password">비밀번호</label>
                        <input type="password" name="password" class="form-control" placeholder="Password" id="password"
                               value="{{ form.password.value|default_if_none:'' }}">
                    </div>
                    <div class="col-12">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" id="rememberMe">
                            <label class="form-check-label" for="rememberMe">ID를 기억합니다.</label>
                        </div>
                    </div>
                    <div class="col-12">
                        <button type="submit" class="btn btn-dark float-end">로그인</button>
                    </div>
                </form>
                <hr class="mt-4">
                <div class="col-12">
                    <p class="text-center mb-0">아직 아이디가 없다면? <a href="{% url 'accounts:signup'%}">회원가입</a></p>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup.html
{% extends "layout.html" %}
{%block content%}
<div class="container" style="margin-top:50px;">
    <div class="row">
        <div class="col-sm-6 offset-sm-3">
            {% include "_form.html" with form_title="회원가입" submit_label="회원가입" %}
        </div>
    </div>
</div>
{%endblock%}